name: Set Heroku Stack to Container
on:
  workflow_dispatch:

jobs:
  set-stack:
    runs-on: ubuntu-latest
    steps:
      - name: Set Heroku stack to container
        run: |
          curl -s -X PATCH https://api.heroku.com/apps/activepieces-f072d4fb20e0 \
          -H "Content-Type: application/json" \
          -H "Accept: application/vnd.heroku+json; version=3" \
          -H "Authorization: Bearer ${{ secrets.HEROKU_API_KEY }}" \
          -d '{"build_stack": "container"}'
